# Generated by Django 4.1.7 on 2023-03-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0003_aluno_votos'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='avatar',
            field=models.CharField(default='votacao/static/media', max_length=100),
        ),
    ]
