# Generated by Django 4.1.7 on 2023-04-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0007_alter_aluno_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='avatar',
            field=models.ImageField(default='static/media/user.png', upload_to=''),
        ),
    ]
